[package]
name = "clash_yaml"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
anyhow = "1.0.79"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
