name: Rust

on:
  watch:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 0/1 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.0    
    - name: Run
      run: cargo run --verbose
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Git commnit and push
      run: |
        git config --global user.email sunclx@gmail.com
        git config --global user.name sunclx
        git add .
        git status | grep -q "nothing to commit" && echo "没有更新内容，无需commit" || git commit -m "cargo run auto" 
        git push
    # git commit --allow-empty -m "cargo run auto" -a
